wrapperVersion=3.3.4
distributionType=only-script
#distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.14/apache-maven-3.9.14-bin.zip
#distributionUrl=https://repo.huaweicloud.com/apache/maven/maven-3/3.9.14/binaries/apache-maven-3.9.14-bin.zip

# 官方地址（默认）
#distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.16/apache-maven-3.9.16-bin.zip
# 阿里云镜像（国内推荐）
distributionUrl=https://maven.aliyun.com/repository/public/org/apache/maven/apache-maven/3.9.16/apache-maven-3.9.16-bin.zip
# 腾讯云镜像
# distributionUrl=https://mirrors.cloud.tencent.com/nexus/repository/maven-public/org/apache/maven/apache-maven/3.9.16/apache-maven-3.9.16-bin.zip
# 华为云镜像
# https://repo.huaweicloud.com/apache/maven/maven-3/3.9.14/binaries/apache-maven-3.9.14-bin.zip