<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>io.github.stylesmile</groupId>
        <artifactId>fastboot-parent</artifactId>
        <version>2.12.1</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.github.stylesmile</groupId>
    <artifactId>fastboot-ai</artifactId>
    <version>2.12.1</version>
    <name>fastboot-ai</name>
    <packaging>pom</packaging>
    <description>ai integrations for fastboot</description>
    <url>https://github.com/stylesmile/fastboot</url>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <modules>
        <module>fastboot-openai</module>
        <module>fastboot-milvus</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.theokanning.openai-gpt3-java</groupId>
                <artifactId>service</artifactId>
                <version>0.18.2</version>
            </dependency>
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp</artifactId>
                <version>4.12.0</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>fastjson</artifactId>
                <version>1.2.83</version>
            </dependency>
            <dependency>
                <groupId>io.milvus</groupId>
                <artifactId>milvus-sdk-java</artifactId>
                <version>2.6.20</version>
            </dependency>
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>4.13.2</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>stylesmile</id>
            <name>Stylesmile</name>
            <email>3239866994@qq.com</email>
            <roles>
                <role>Project Manager</role>
                <role>Architect</role>
            </roles>
            <timezone>+8</timezone>
        </developer>
    </developers>

    <scm>
        <connection>https://github.com/stylesmile/fastboot.git</connection>
        <developerConnection>scm:git:ssh://git@github.com:stylesmile/fastboot.git</developerConnection>
        <url>https://github.com/stylesmile/fastboot</url>
    </scm>
</project>
